/* =========================================================================
 * 语言文件（单一来源）：所有 UI 文本的固定键 → 各语言译文
 * 键名全部为简短英文；缺失键回退中文，再回退键名本身。
 * ======================================================================= */
var LANGS = {
  zh: {
    // —— 通用 ——
    'common.ok': '确定', 'common.cancel': '取消', 'common.delete': '删除', 'common.rename': '重命名',
    'common.new': '新建', 'common.open': '打开', 'common.save': '保存', 'common.undo': '撤回', 'common.redo': '重做',
    'common.close': '关闭', 'common.color': '颜色',
    // —— 菜单 ——
    'menu.file': '文件', 'menu.edit': '编辑', 'menu.lang': '语言', 'menu.about': '关于',
    'menu.openEllipsis': '打开…', 'menu.saveAs': '另存为…', 'menu.exportAnim': '导出动画…', 'menu.clear': '清空',
    'menu.selectAll': '全选', 'menu.deleteSelected': '删除选中', 'menu.group': '建立组',
    // —— 面板 / 选项卡 ——
    'panel.particleList': '粒子列表',
    'tab.props': '属性', 'tab.fx': '函数对象', 'tab.texture': '贴图 / UV',
    // —— 场景工具栏 ——
    'tool.select': '选择（框选）', 'tool.move': '移动', 'tool.rotate': '旋转',
    'tool.pencil': '铅笔（点按放置）', 'tool.line': '直线', 'tool.circle': '圆', 'tool.rect': '矩形', 'tool.freehand': '手绘',
    // —— 属性面板 ——
    'props.opacity': '透明度', 'props.scale': '缩放', 'props.glow': '发光', 'props.light': '光照等级',
    'props.life': '寿命(tick)', 'props.lifeHint': '-1 或留空 = 无限（活到动画结束）',
    'prop.pos': '位置', 'prop.rot': '旋转', 'prop.vel': '速度', 'prop.col': '颜色', 'prop.scl': '缩放',
    // —— 函数对象 ——
    'fx.addPresetTitle': '按预设新建函数对象', 'fx.noSelection': '选中一个函数对象以编辑属性',
    'fx.exprError': '表达式错误', 'fx.name': '名称 ', 'fx.sampleCount': '采样数 ', 'fx.center': '中心点 ',
    'fx.duration': '时长 ', 'fx.interval': ' 间隔 ', 'fx.codeBlock': '公式代码块', 'fx.puzzle': '🧩 拼图',
    'fx.puzzleHint': '以拼图形式编辑代码段', 'fx.varList': '变量列表',
    'fx.collapseKf': '折叠关键帧列表', 'fx.expandKf': '展开关键帧列表',
    'fx.kfSyncedHint': '有关键帧：值由时间轴驱动（删除全部关键帧后可编辑表达式）',
    'fx.varNameError': '变量名错误', 'fx.varNameReserved': '变量名 {0} 是属性保留字',
    'fx.kfCountHint': '关键帧数（点击 ▸ 展开查看）', 'fx.addKf': '+ 关键帧',
    'fx.defaultName': '函数对象',
    'fx.preset.blank': '空', 'fx.preset.sin': 'SIN 函数', 'fx.preset.sphere': '球体', 'fx.preset.cube': '立方体',
    'fx.preset.torus': '甜甜圈', 'fx.preset.cylinder': '圆柱', 'fx.preset.cone': '圆锥', 'fx.preset.helix': '螺旋线',
    'fx.preset.plane': '平面网格', 'fx.preset.circle': '圆周', 'fx.preset.disc': '圆盘', 'fx.preset.star': '星形',
    'fx.preset.rising_smoke': '循环上升烟雾',
    'fx.param.amp': '振幅', 'fx.param.freq': '频率', 'fx.param.wid': '宽度', 'fx.param.rad': '半径',
    'fx.param.edge': '边长', 'fx.param.major': '大半径', 'fx.param.minor': '管半径', 'fx.param.m': '密度',
    'fx.param.k': '圆环密度', 'fx.param.h': '高度', 'fx.param.cr': '顶/底密度', 'fx.param.spd': '上升速度',
    'fx.param.w': '宽', 'fx.param.d': '深', 'fx.param.diskR': '半径',
    // —— 贴图编辑器 ——
    'tex.tool.select': '矩形选区', 'tex.tool.move': '移动选区（在选区内拖动移动内容）',
    'tex.tool.pencil': '铅笔', 'tex.tool.bucket': '油漆桶', 'tex.tool.picker': '滴管（按住 Alt 临时切换）',
    'tex.upload': '上传贴图', 'tex.export': '导出',
    'tex.selectHint': '选中对象以编辑贴图 / UV',
    'tex.namePrompt': '贴图名称', 'tex.renameTitle': '重命名贴图', 'tex.newName': '新名称',
    'tex.deleteTitle': '删除贴图', 'tex.resize': '修改大小', 'tex.resizeTitle': '修改大小 · {0}',
    'tex.width': '宽', 'tex.height': '高', 'tex.texLabel': '贴图 ', 'tex.none': '无', 'tex.uvMode': 'UV 模式 ',
    'tex.px': '像素', 'tex.multiply': '乘以', 'tex.perSec': '/ 秒', 'tex.maxFrames': '最大帧数',
    'tex.maxFramesHint': '0 或 1 = 自动（按 UV 步长算满）；>1 = 最大上限',
    'tex.texSize': '贴图大小', 'tex.uvStart': 'UV 起点', 'tex.uvSize': 'UV 大小', 'tex.uvStep': 'UV 步长',
    'tex.fps': '帧率',
    'uv.mode.static': '静态', 'uv.mode.fill': '填充', 'uv.mode.animated': '动画',
    // —— 时间轴 ——
    'timeline.resizeTitle': '拖拽调整时间轴模块高度', 'timeline.speed': '速度', 'timeline.loop': '循环',
    'timeline.easing': '缓动函数', 'timeline.play': '▶ 播放', 'timeline.pause': '⏸ 暂停',
    // —— 粒子列表 / 树 ——
    'tree.addParticle': '添加粒子',
    'tree.hint': '提示', 'tree.selectParticlesFirst': '请先选中粒子', 'tree.derivedNoGroup': '派生粒子不可建立普通组',
    'tree.empty': '暂无粒子，请使用右侧工具绘制', 'tree.dblclickRename': '双击重命名',
    'tree.trackCount': '{0} 轨道', 'tree.deleteParticle': '删除粒子', 'tree.addKfHint': '添加关键帧（当前时间）',
    'tree.memberCount': '{0} 成员', 'tree.deleteGroup': '删除组及其粒子',
    'tree.particleListCount': '粒子列表 ({0})', 'tree.fxParticleCount': '{0} 粒子', 'tree.deleteFx': '删除函数对象',
    'tree.deleteKf': '删除关键帧', 'tree.editKf': '编辑关键帧 · {0} {1}', 'tree.time': '时间', 'tree.value': '值',
    'tree.easingLabel': '缓动',
    'draw.countLabel': '粒子数量',
    // —— 文件流程 ——
    'newProject.title': '新建项目', 'newProject.name': '项目名称',
    'confirm.unsavedTitle': '未保存的更改', 'confirm.unsavedMsg': '当前工程有未保存的修改。',
    'confirm.discard': '不保存', 'confirm.saveAnd': '保存并',
    'filePicker.project': 'ParticleDrawing 工程', 'filePicker.projectFile': '工程文件',
    // —— 关于 ——
    'about.title': '关于 ParticleDrawing',
    'about.desc': 'ParticleDrawing 粒子动画编辑器 — 用于创作 .pdraw 动画并在 Minecraft 中播放。',
    'about.developer': '开发者',
    // —— 缓动编辑器 ——
    'easing.editTitle': '编辑缓动函数', 'easing.editorTitle': '缓动函数编辑器', 'easing.presets': '预设…',
    // —— 悬浮窗 ——
    'fwin.minimize': '最小化',
    // —— 默认命名 ——
    'default.particleName': '粒子', 'default.groupName': '组',
    // —— 贴图提示 ——
    'alert.uploadFailed': '上传失败', 'alert.texTooBig': '贴图超过 5MB 上限', 'alert.pngOnly': '仅支持 PNG 格式',
    'alert.pngParseFail': '无法解析该 PNG 文件', 'alert.exportFailed': '导出失败',
    'alert.noTexture': '当前无贴图，请先新建或上传', 'alert.pngGenFail': '无法生成 PNG',
    'alert.renameFailed': '重命名失败', 'alert.nameEmpty': '名称不能为空',
    'alert.texExists': '已存在同名贴图「{0}」',
    'alert.deleteTexConfirm': '确定删除「{0}」吗？\n引用它的对象将恢复为无贴图。',
    // —— 表达式错误 ——
    'err.dotNeedsVec': 'dot 需要向量', 'err.crossNeedsVec': 'cross 需要向量', 'err.normNeedsVec': 'norm 需要向量',
    'err.rotAxisNeedsVec': 'rotAxis 需要向量轴', 'err.negType': '一元负号类型不支持',
    'err.opAdd': '运算符 + 类型不匹配', 'err.opSub': '运算符 - 类型不匹配', 'err.opMul': '运算符 * 类型不匹配',
    'err.opDiv': '运算符 / 类型不匹配', 'err.opMod': '运算符 % 仅支持标量', 'err.opPow': '运算符 ^ 仅支持标量',
    'err.unknownOp': '未知运算符: {0}', 'err.compNeedsVec': '分量访问需要向量', 'err.unknownVar': '未知变量: {0}',
    'err.propScalar': '属性 {0} 需要标量值', 'err.missingEq': '表达式缺少 = : {0}',
    'err.assignCount': '赋值数量不匹配', 'err.assignCount2': '赋值数量不匹配: {0}',
    'err.unknownExprNode': '未知表达式节点: {0}', 'err.unknownStmt': '未知语句块: {0}',
    'err.exprNeed': '表达式缺少 {0} : {1}', 'err.exprEnd': '表达式意外结束',
    'err.funcNoParen': '函数缺少括号: {0}', 'err.unexpectedTok': '意外符号: {0}',
    'err.exprExtra': '表达式有多余内容: {0}', 'err.stmtMissingEq': '语句缺少 = : {0}',
    'err.unknownPack': '无法识别的打包赋值: {0}', 'err.unknownUnpack': '无法识别的向量拆包: {0}',
    'err.glowBinary': '发光赋值只能是 0 或 1: {0}',
    'err.varCycle': '变量循环引用: {0}', 'err.varReserved': '变量名 {0} 是属性保留字，请换名',
    // —— 拼图 UI ——
    'blk.title': '拼图代码块', 'blk.scene': '场景', 'blk.code': '代码',
    'blk.lensHint': '拖动到拼图上查看含义',
    'blk.openFailTitle': '无法用拼图打开', 'blk.parseFail': '代码解析失败\n{0}\n\n请先在文本视图修正代码。',
    'blk.varExprErrTitle': '变量表达式错误', 'blk.varExprErr': '变量 {0} 的表达式解析失败：{1}',
    'blk.start': '起点', 'blk.fragment': '碎片', 'blk.block': '积木',
    'blk.sampleCount': '采样数', 'blk.varHasKf': '{0}（有关键帧，由时间轴驱动）',
    'blk.attrRefHint': '拖入表达式以引用属性 {0}',
    'blk.clickSwapComp': '点击切换分量', 'blk.addTerm': '+ 项', 'blk.addTermHint': '拖入数值或运算符以追加',
    'blk.glowOn': '发光:开', 'blk.glowOff': '发光:关', 'blk.colorPicker': '取色器',
    'blk.chain': '算式', 'blk.chainDesc': '动态算式（可追加项）',
    'blk.constNum': '常量数值', 'blk.var': '变量', 'blk.op': '运算符',
    'blk.comp': '.分量', 'blk.compDesc': '取向量的 x/y/z 分量', 'blk.neg': '取负',
    'blk.piInfo': '圆周率 π ≈ 3.14159', 'blk.eInfo': '自然常数 e ≈ 2.71828',
    // —— 拼图：类型 / 内置变量 / 调色板 / 运算符 / 参数 ——
    'blk.type.scalar': '数字', 'blk.type.vec': '向量', 'blk.type.mat': '矩阵', 'blk.type.any': '任意',
    'blk.var.i': '粒子序号（0 ~ n-1）', 'blk.var.n': '采样数（粒子总数）', 'blk.var.t': '当前时间（tick）',
    'blk.pal.pos': '位置 / 速度', 'blk.pal.color': '颜色', 'blk.pal.appearance': '外观', 'blk.pal.math': '数学',
    'blk.pal.vec': '向量', 'blk.pal.mat': '矩阵', 'blk.pal.var': '变量', 'blk.pal.const': '常量',
    'blk.op.add': '加', 'blk.op.sub': '减', 'blk.op.mul': '乘', 'blk.op.div': '除', 'blk.op.mod': '取余', 'blk.op.pow': '幂',
    'blk.arg.angle': '角度', 'blk.arg.value': '值', 'blk.arg.base': '底数', 'blk.arg.exp': '指数',
    'blk.arg.lo': '下界', 'blk.arg.hi': '上界', 'blk.arg.edge': '边界', 'blk.arg.mod': '模',
    'blk.arg.seed': '种子', 'blk.arg.vec': '向量', 'blk.arg.axis': '轴', 'blk.arg.radius': '半径',
    'blk.slot.scale': '缩放', 'blk.slot.light': '光照',
    // —— 拼图：语句块 ——
    'blk.stmt.pos.label': '位置', 'blk.stmt.pos.desc': '设置粒子位置 [x, y, z]',
    'blk.stmt.pos_vec.label': '位置 ← 向量', 'blk.stmt.pos_vec.desc': '用向量设置粒子位置',
    'blk.stmt.vel.label': '速度', 'blk.stmt.vel.desc': '设置粒子速度 [vx, vy, vz]',
    'blk.stmt.vel_vec.label': '速度', 'blk.stmt.vel_vec.desc': '用向量设置粒子速度',
    'blk.stmt.col.label': '颜色', 'blk.stmt.col.desc': '设置粒子颜色 [r, g, b, a]',
    'blk.stmt.scl.label': '缩放', 'blk.stmt.scl.desc': '设置粒子缩放',
    'blk.stmt.glow.label': '发光', 'blk.stmt.glow.desc': '设置粒子是否发光',
    'blk.stmt.light.label': '光照等级', 'blk.stmt.light.desc': '设置粒子光照等级',
    'blk.stmt.attr.label': '设置属性', 'blk.stmt.attr.desc': '设置单个属性值（x/y/z/…）',
    'blk.stmt.set.label': '临时变量', 'blk.stmt.set.desc': '定义临时变量并赋值',
    // —— 拼图：函数说明 ——
    'blk.func.sin.desc': '正弦函数', 'blk.func.cos.desc': '余弦函数', 'blk.func.tan.desc': '正切函数',
    'blk.func.asin.desc': '反正弦函数', 'blk.func.acos.desc': '反余弦函数', 'blk.func.atan.desc': '反正切函数',
    'blk.func.atan2.desc': '反正切函数', 'blk.func.sqrt.desc': '平方根', 'blk.func.abs.desc': '绝对值',
    'blk.func.sign.desc': '符号函数（正 1 / 负 -1 / 零 0）', 'blk.func.exp.desc': '指数函数 e^x',
    'blk.func.log.desc': '以 10 为底的常用对数', 'blk.func.ln.desc': '以 e 为底的自然对数',
    'blk.func.floor.desc': '向下取整', 'blk.func.ceil.desc': '向上取整', 'blk.func.round.desc': '四舍五入',
    'blk.func.fract.desc': '取小数部分', 'blk.func.pow.desc': '幂运算',
    'blk.func.min.desc': '取两者较小值', 'blk.func.max.desc': '取两者较大值',
    'blk.func.clamp.desc': '把值限制在区间内', 'blk.func.lerp.desc': '线性插值 a→b',
    'blk.func.step.desc': '阶跃（x≥边界返回 1，否则 0）', 'blk.func.smoothstep.desc': '平滑阶跃插值',
    'blk.func.mod.desc': '取模（GLSL 语义）', 'blk.func.random.desc': '随机数（0 到 1 之间）',
    'blk.func.rand.desc': '固定伪随机（同一种子恒返回相同的 [0,1) 值）',
    'blk.func.vec.desc': '由分量构造向量', 'blk.func.dot.desc': '向量点积', 'blk.func.cross.desc': '向量叉积',
    'blk.func.len.desc': '向量长度', 'blk.func.norm.desc': '向量归一化',
    'blk.func.rotX.desc': '绕 X 轴旋转矩阵', 'blk.func.rotY.desc': '绕 Y 轴旋转矩阵', 'blk.func.rotZ.desc': '绕 Z 轴旋转矩阵',
    'blk.func.rotAxis.desc': '绕任意轴旋转矩阵', 'blk.func.polar.desc': '极坐标转向量',
    'blk.func.sphere.desc': '球坐标转向量', 'blk.func.torus.desc': '环面坐标转向量',
  },
  en: {
    // —— 通用 ——
    'common.ok': 'OK', 'common.cancel': 'Cancel', 'common.delete': 'Delete', 'common.rename': 'Rename',
    'common.new': 'New', 'common.open': 'Open', 'common.save': 'Save', 'common.undo': 'Undo', 'common.redo': 'Redo',
    'common.close': 'Close', 'common.color': 'Color',
    // —— 菜单 ——
    'menu.file': 'File', 'menu.edit': 'Edit', 'menu.lang': 'Language', 'menu.about': 'About',
    'menu.openEllipsis': 'Open…', 'menu.saveAs': 'Save As…', 'menu.exportAnim': 'Export Animation…', 'menu.clear': 'Clear',
    'menu.selectAll': 'Select All', 'menu.deleteSelected': 'Delete Selected', 'menu.group': 'Group',
    // —— 面板 / 选项卡 ——
    'panel.particleList': 'Particle List',
    'tab.props': 'Properties', 'tab.fx': 'Function Object', 'tab.texture': 'Texture / UV',
    // —— 场景工具栏 ——
    'tool.select': 'Select (Box)', 'tool.move': 'Move', 'tool.rotate': 'Rotate',
    'tool.pencil': 'Pencil (Click to Place)', 'tool.line': 'Line', 'tool.circle': 'Circle', 'tool.rect': 'Rectangle', 'tool.freehand': 'Freehand',
    // —— 属性面板 ——
    'props.opacity': 'Opacity', 'props.scale': 'Scale', 'props.glow': 'Glow', 'props.light': 'Light Level',
    'props.life': 'Life (tick)', 'props.lifeHint': '-1 or empty = infinite (lives until animation ends)',
    'prop.pos': 'Position', 'prop.rot': 'Rotation', 'prop.vel': 'Velocity', 'prop.col': 'Color', 'prop.scl': 'Scale',
    // —— 函数对象 ——
    'fx.addPresetTitle': 'Create function object from preset', 'fx.noSelection': 'Select a function object to edit its properties',
    'fx.exprError': 'Expression Error', 'fx.name': 'Name ', 'fx.sampleCount': 'Sample Count ', 'fx.center': 'Center ',
    'fx.duration': 'Duration ', 'fx.interval': ' Interval ', 'fx.codeBlock': 'Code Block', 'fx.puzzle': '🧩 Puzzle',
    'fx.puzzleHint': 'Edit code as puzzle blocks', 'fx.varList': 'Variables',
    'fx.collapseKf': 'Collapse keyframes', 'fx.expandKf': 'Expand keyframes',
    'fx.kfSyncedHint': 'Has keyframes: value is driven by the timeline (remove all keyframes to edit the expression)',
    'fx.varNameError': 'Invalid Variable Name', 'fx.varNameReserved': 'Variable name {0} is a reserved attribute name',
    'fx.kfCountHint': 'Keyframe count (click ▸ to expand)', 'fx.addKf': '+ Keyframe',
    'fx.defaultName': 'Function Object',
    'fx.preset.blank': 'Empty', 'fx.preset.sin': 'SIN Function', 'fx.preset.sphere': 'Sphere', 'fx.preset.cube': 'Cube',
    'fx.preset.torus': 'Torus', 'fx.preset.cylinder': 'Cylinder', 'fx.preset.cone': 'Cone', 'fx.preset.helix': 'Helix',
    'fx.preset.plane': 'Plane Grid', 'fx.preset.circle': 'Circle', 'fx.preset.disc': 'Disc', 'fx.preset.star': 'Star',
    'fx.preset.rising_smoke': 'Rising Smoke',
    'fx.param.amp': 'Amplitude', 'fx.param.freq': 'Frequency', 'fx.param.wid': 'Width', 'fx.param.rad': 'Radius',
    'fx.param.edge': 'Edge', 'fx.param.major': 'Major R', 'fx.param.minor': 'Tube R', 'fx.param.m': 'Density',
    'fx.param.k': 'Ring Density', 'fx.param.h': 'Height', 'fx.param.cr': 'Top/Bottom Density', 'fx.param.spd': 'Rise Speed',
    'fx.param.w': 'Width', 'fx.param.d': 'Depth', 'fx.param.diskR': 'Radius',
    // —— 贴图编辑器 ——
    'tex.tool.select': 'Rectangle Selection', 'tex.tool.move': 'Move Selection (drag inside to move content)',
    'tex.tool.pencil': 'Pencil', 'tex.tool.bucket': 'Bucket', 'tex.tool.picker': 'Eyedropper (hold Alt)',
    'tex.upload': 'Upload Texture', 'tex.export': 'Export',
    'tex.selectHint': 'Select an object to edit texture / UV',
    'tex.namePrompt': 'Texture Name', 'tex.renameTitle': 'Rename Texture', 'tex.newName': 'New Name',
    'tex.deleteTitle': 'Delete Texture', 'tex.resize': 'Resize', 'tex.resizeTitle': 'Resize · {0}',
    'tex.width': 'Width', 'tex.height': 'Height', 'tex.texLabel': 'Texture ', 'tex.none': 'None', 'tex.uvMode': 'UV Mode ',
    'tex.px': 'px', 'tex.multiply': 'multiply', 'tex.perSec': '/ sec', 'tex.maxFrames': 'Max Frames',
    'tex.maxFramesHint': '0 or 1 = auto (fill by UV step); >1 = max limit',
    'tex.texSize': 'Texture Size', 'tex.uvStart': 'UV Start', 'tex.uvSize': 'UV Size', 'tex.uvStep': 'UV Step',
    'tex.fps': 'Frame Rate',
    'uv.mode.static': 'Static', 'uv.mode.fill': 'Fill', 'uv.mode.animated': 'Animated',
    // —— 时间轴 ——
    'timeline.resizeTitle': 'Drag to resize timeline module', 'timeline.speed': 'Speed', 'timeline.loop': 'Loop',
    'timeline.easing': 'Easing', 'timeline.play': '▶ Play', 'timeline.pause': '⏸ Pause',
    // —— 粒子列表 / 树 ——
    'tree.addParticle': 'Add Particle',
    'tree.hint': 'Notice', 'tree.selectParticlesFirst': 'Please select particles first', 'tree.derivedNoGroup': 'Derived particles cannot form a regular group',
    'tree.empty': 'No particles yet. Use the tools on the right to draw.',
    'tree.dblclickRename': 'Double-click to rename',
    'tree.trackCount': '{0} tracks', 'tree.deleteParticle': 'Delete Particle', 'tree.addKfHint': 'Add keyframe (at current time)',
    'tree.memberCount': '{0} members', 'tree.deleteGroup': 'Delete Group and Its Particles',
    'tree.particleListCount': 'Particle List ({0})', 'tree.fxParticleCount': '{0} particles', 'tree.deleteFx': 'Delete Function Object',
    'tree.deleteKf': 'Delete Keyframe', 'tree.editKf': 'Edit Keyframe · {0} {1}', 'tree.time': 'Time', 'tree.value': 'Value',
    'tree.easingLabel': 'Easing',
    'draw.countLabel': 'Particle Count',
    // —— 文件流程 ——
    'newProject.title': 'New Project', 'newProject.name': 'Project Name',
    'confirm.unsavedTitle': 'Unsaved Changes', 'confirm.unsavedMsg': 'The current project has unsaved changes.',
    'confirm.discard': "Don't Save", 'confirm.saveAnd': 'Save & ',
    'filePicker.project': 'ParticleDrawing Project', 'filePicker.projectFile': 'Project File',
    // —— 关于 ——
    'about.title': 'About ParticleDrawing',
    'about.desc': 'ParticleDrawing Particle Animation Editor — create .pdraw animations and play them in Minecraft.',
    'about.developer': 'Developer',
    // —— 缓动编辑器 ——
    'easing.editTitle': 'Edit Easing', 'easing.editorTitle': 'Easing Editor', 'easing.presets': 'Presets…',
    // —— 悬浮窗 ——
    'fwin.minimize': 'Minimize',
    // —— 默认命名 ——
    'default.particleName': 'Particle', 'default.groupName': 'Group',
    // —— 贴图提示 ——
    'alert.uploadFailed': 'Upload Failed', 'alert.texTooBig': 'Texture exceeds the 5MB limit', 'alert.pngOnly': 'Only PNG format is supported',
    'alert.pngParseFail': 'Unable to parse this PNG file', 'alert.exportFailed': 'Export Failed',
    'alert.noTexture': 'No texture available. Create or upload one first.', 'alert.pngGenFail': 'Unable to generate PNG',
    'alert.renameFailed': 'Rename Failed', 'alert.nameEmpty': 'Name cannot be empty',
    'alert.texExists': 'A texture named "{0}" already exists',
    'alert.deleteTexConfirm': 'Delete "{0}"?\nObjects referencing it will revert to no texture.',
    // —— 表达式错误 ——
    'err.dotNeedsVec': 'dot requires a vector', 'err.crossNeedsVec': 'cross requires a vector', 'err.normNeedsVec': 'norm requires a vector',
    'err.rotAxisNeedsVec': 'rotAxis requires a vector axis', 'err.negType': 'unary minus not supported for this type',
    'err.opAdd': 'operator + type mismatch', 'err.opSub': 'operator - type mismatch', 'err.opMul': 'operator * type mismatch',
    'err.opDiv': 'operator / type mismatch', 'err.opMod': 'operator % only supports scalars', 'err.opPow': 'operator ^ only supports scalars',
    'err.unknownOp': 'unknown operator: {0}', 'err.compNeedsVec': 'component access requires a vector', 'err.unknownVar': 'unknown variable: {0}',
    'err.propScalar': 'property {0} requires a scalar value', 'err.missingEq': 'expression missing = : {0}',
    'err.assignCount': 'assignment count mismatch', 'err.assignCount2': 'assignment count mismatch: {0}',
    'err.unknownExprNode': 'unknown expression node: {0}', 'err.unknownStmt': 'unknown statement block: {0}',
    'err.exprNeed': 'expression missing {0} : {1}', 'err.exprEnd': 'unexpected end of expression',
    'err.funcNoParen': 'function missing parentheses: {0}', 'err.unexpectedTok': 'unexpected token: {0}',
    'err.exprExtra': 'extra content in expression: {0}', 'err.stmtMissingEq': 'statement missing = : {0}',
    'err.unknownPack': 'unrecognized packed assignment: {0}', 'err.unknownUnpack': 'unrecognized vector unpack: {0}',
    'err.glowBinary': 'glow assignment must be 0 or 1: {0}',
    'err.varCycle': 'variable circular reference: {0}', 'err.varReserved': 'Variable name {0} is a reserved attribute name, please rename',
    // —— 拼图 UI ——
    'blk.title': 'Puzzle Code Blocks', 'blk.scene': 'Scene', 'blk.code': 'Code',
    'blk.lensHint': 'Drag onto a block to see its meaning',
    'blk.openFailTitle': 'Cannot Open in Puzzle View', 'blk.parseFail': 'Failed to parse code\n{0}\n\nPlease fix the code in text view first.',
    'blk.varExprErrTitle': 'Variable Expression Error', 'blk.varExprErr': 'Failed to parse expression of variable {0}: {1}',
    'blk.start': 'Start', 'blk.fragment': 'Fragment', 'blk.block': 'Block',
    'blk.sampleCount': 'Sample Count', 'blk.varHasKf': '{0} (has keyframes, driven by the timeline)',
    'blk.attrRefHint': 'Drop an expression to reference property {0}',
    'blk.clickSwapComp': 'Click to cycle component', 'blk.addTerm': '+ Term', 'blk.addTermHint': 'Drop a number or operator to append',
    'blk.glowOn': 'Glow: On', 'blk.glowOff': 'Glow: Off', 'blk.colorPicker': 'Color Picker',
    'blk.chain': 'Expression', 'blk.chainDesc': 'Dynamic expression (appendable)',
    'blk.constNum': 'Constant number', 'blk.var': 'Variable', 'blk.op': 'Operator',
    'blk.comp': '.Component', 'blk.compDesc': 'Take x/y/z component of a vector', 'blk.neg': 'Negate',
    'blk.piInfo': 'Pi π ≈ 3.14159', 'blk.eInfo': 'Euler\'s number e ≈ 2.71828',
    // —— 拼图：类型 / 内置变量 / 调色板 / 运算符 / 参数 ——
    'blk.type.scalar': 'Number', 'blk.type.vec': 'Vector', 'blk.type.mat': 'Matrix', 'blk.type.any': 'Any',
    'blk.var.i': 'Particle index (0 ~ n-1)', 'blk.var.n': 'Sample count (total particles)', 'blk.var.t': 'Current time (tick)',
    'blk.pal.pos': 'Position / Velocity', 'blk.pal.color': 'Color', 'blk.pal.appearance': 'Appearance', 'blk.pal.math': 'Math',
    'blk.pal.vec': 'Vector', 'blk.pal.mat': 'Matrix', 'blk.pal.var': 'Variable', 'blk.pal.const': 'Constants',
    'blk.op.add': 'Add', 'blk.op.sub': 'Subtract', 'blk.op.mul': 'Multiply', 'blk.op.div': 'Divide', 'blk.op.mod': 'Modulo', 'blk.op.pow': 'Power',
    'blk.arg.angle': 'Angle', 'blk.arg.value': 'Value', 'blk.arg.base': 'Base', 'blk.arg.exp': 'Exponent',
    'blk.arg.lo': 'Lower bound', 'blk.arg.hi': 'Upper bound', 'blk.arg.edge': 'Edge', 'blk.arg.mod': 'Modulus',
    'blk.arg.seed': 'Seed', 'blk.arg.vec': 'Vector', 'blk.arg.axis': 'Axis', 'blk.arg.radius': 'Radius',
    'blk.slot.scale': 'Scale', 'blk.slot.light': 'Light',
    // —— 拼图：语句块 ——
    'blk.stmt.pos.label': 'Position', 'blk.stmt.pos.desc': 'Set particle position [x, y, z]',
    'blk.stmt.pos_vec.label': 'Position ← Vector', 'blk.stmt.pos_vec.desc': 'Set position from a vector',
    'blk.stmt.vel.label': 'Velocity', 'blk.stmt.vel.desc': 'Set particle velocity [vx, vy, vz]',
    'blk.stmt.vel_vec.label': 'Velocity', 'blk.stmt.vel_vec.desc': 'Set velocity from a vector',
    'blk.stmt.col.label': 'Color', 'blk.stmt.col.desc': 'Set particle color [r, g, b, a]',
    'blk.stmt.scl.label': 'Scale', 'blk.stmt.scl.desc': 'Set particle scale',
    'blk.stmt.glow.label': 'Glow', 'blk.stmt.glow.desc': 'Toggle particle glow',
    'blk.stmt.light.label': 'Light Level', 'blk.stmt.light.desc': 'Set particle light level',
    'blk.stmt.attr.label': 'Set Property', 'blk.stmt.attr.desc': 'Set a single property value (x/y/z/…)',
    'blk.stmt.set.label': 'Local Variable', 'blk.stmt.set.desc': 'Define a local variable and assign',
    // —— 拼图：函数说明 ——
    'blk.func.sin.desc': 'Sine function', 'blk.func.cos.desc': 'Cosine function', 'blk.func.tan.desc': 'Tangent function',
    'blk.func.asin.desc': 'Arcsine function', 'blk.func.acos.desc': 'Arccosine function', 'blk.func.atan.desc': 'Arctangent function',
    'blk.func.atan2.desc': 'Arctangent function', 'blk.func.sqrt.desc': 'Square root', 'blk.func.abs.desc': 'Absolute value',
    'blk.func.sign.desc': 'Sign function (1 / -1 / 0)', 'blk.func.exp.desc': 'Exponential e^x',
    'blk.func.log.desc': 'Base-10 logarithm', 'blk.func.ln.desc': 'Natural logarithm',
    'blk.func.floor.desc': 'Round down', 'blk.func.ceil.desc': 'Round up', 'blk.func.round.desc': 'Round to nearest',
    'blk.func.fract.desc': 'Fractional part', 'blk.func.pow.desc': 'Power',
    'blk.func.min.desc': 'Minimum of two values', 'blk.func.max.desc': 'Maximum of two values',
    'blk.func.clamp.desc': 'Clamp value to a range', 'blk.func.lerp.desc': 'Linear interpolation a→b',
    'blk.func.step.desc': 'Step (returns 1 when x ≥ edge, else 0)', 'blk.func.smoothstep.desc': 'Smoothstep interpolation',
    'blk.func.mod.desc': 'Modulo (GLSL semantics)', 'blk.func.random.desc': 'Random number (0 to 1)',
    'blk.func.rand.desc': 'Deterministic pseudo-random (same seed returns the same [0,1) value)',
    'blk.func.vec.desc': 'Construct vector from components', 'blk.func.dot.desc': 'Vector dot product', 'blk.func.cross.desc': 'Vector cross product',
    'blk.func.len.desc': 'Vector length', 'blk.func.norm.desc': 'Normalize vector',
    'blk.func.rotX.desc': 'Rotation matrix around X', 'blk.func.rotY.desc': 'Rotation matrix around Y', 'blk.func.rotZ.desc': 'Rotation matrix around Z',
    'blk.func.rotAxis.desc': 'Rotation matrix around an axis', 'blk.func.polar.desc': 'Polar to vector',
    'blk.func.sphere.desc': 'Spherical to vector', 'blk.func.torus.desc': 'Torus to vector',
  },
};
