/* =========================================================================
 * 语言文件（单一来源）：所有 UI 文本的固定键 → 各语言译文
 * 键名全部为简短英文；缺失键回退中文，再回退键名本身。
 * ======================================================================= */
export var LANGS = {
  zh: {
    // —— 通用 ——
    'common.ok': '确定', 'common.cancel': '取消', 'common.delete': '删除', 'common.rename': '重命名',
    'common.new': '新建', 'common.open': '打开', 'common.save': '保存', 'common.undo': '撤回', 'common.redo': '重做',
    'common.close': '关闭', 'common.color': '颜色',
    // —— 菜单 ——
    'menu.file': '文件', 'menu.import': '导入', 'menu.edit': '编辑', 'menu.lang': '语言', 'menu.about': '关于',
    'menu.openEllipsis': '打开…', 'menu.saveAs': '另存为…', 'menu.exportAnim': '导出动画…', 'menu.clear': '清空',
    'menu.selectAll': '全选', 'menu.deleteSelected': '删除选中', 'menu.group': '建立组',
    // —— 面板 / 选项卡 ——
    'panel.particleList': '粒子列表',
    'mobile.panels': '属性 / 函数 / 贴图', 'mobile.timeline': '时间轴',
    'tab.props': '属性', 'tab.fx': '函数对象', 'tab.texture': '贴图 / UV', 'tab.import': '导入',
    // —— 场景工具栏 ——
    'tool.select': '选择（框选）', 'tool.move': '移动', 'tool.rotate': '旋转',
    'tool.rotateSpin': '旋转（自转模式，按 R 切换）', 'tool.rotateOrbit': '旋转（公转模式，按 R 切换）',
    'rotMode.spin': '自', 'rotMode.orbit': '公',
    'spinSpace.world': 'W', 'spinSpace.local': 'L', 'spinSpace.hint': 'W：世界坐标系\nL：局部坐标系',
    'rotSpace.world': 'W', 'rotSpace.local': 'L', 'rotSpace.hint': 'W：世界坐标系\nL：局部坐标系',
    'tool.pencil': '铅笔（点按放置）', 'tool.line': '直线', 'tool.circle': '圆', 'tool.rect': '矩形', 'tool.freehand': '手绘',
    // —— 属性面板 ——
    'props.opacity': '透明度', 'props.scale': '缩放', 'props.glow': '发光', 'props.light': '光照等级',
    'props.life': '寿命(tick)', 'props.lifeHint': '-1 或留空 = 无限（活到动画结束）',
    'prop.pos': '位置', 'prop.target': '目标', 'prop.rot': '公转', 'prop.rotCam': '旋转', 'prop.spin': '自转', 'prop.center': '公转中心', 'prop.vel': '速度', 'prop.col': '颜色', 'prop.scl': '缩放', 'prop.fov': 'FOV',
    // —— 函数对象 ——
    'fx.addPresetTitle': '按预设新建函数对象', 'fx.noSelection': '选中一个函数对象以编辑属性',
    'fx.exprError': '表达式错误', 'fx.sampleCount': '采样数 ', 'fx.center': '中心点 ',
    'fx.noVars': '暂无变量',
    'fx.duration': '时长 ', 'fx.interval': ' 间隔 ', 'fx.codeBlock': '公式代码块', 'fx.puzzle': '🧩 拼图',
    'fx.setupBlock': '初始化', 'fx.processBlock': '粒子每帧', 'fx.funcsBlock': '顶层函数', 'fx.seed': '随机种子 ',
    'fx.fastMath': '快速数学近似',
    'fx.puzzleHint': '以拼图形式编辑代码段', 'fx.varList': '变量列表', 'fx.addVar': '新建变量',
    'fx.varListHint': '数值由时间轴驱动',
    'fx.collapseKf': '折叠关键帧列表', 'fx.expandKf': '展开关键帧列表',
    'fx.kfSyncedHint': '有关键帧：值由时间轴驱动（删除全部关键帧后可编辑表达式）',
    'fx.varNameError': '变量名错误', 'fx.varNameReserved': '变量名 {0} 是属性保留字',
    'fx.varNameInvalid': '变量名 {0} 无效（需以字母或下划线开头，仅含字母、数字、下划线）', 'fx.varNameExists': '变量名 {0} 已存在',
    'fx.kfCountHint': '关键帧数（点击 ▸ 展开查看）', 'fx.addKf': '+ 关键帧',
    'fx.defaultName': '函数对象',
    'fx.preset.blank': '空', 'fx.preset.sin': 'SIN 函数', 'fx.preset.sphere': '球体', 'fx.preset.cube': '立方体',
    'fx.preset.torus': '甜甜圈', 'fx.preset.cylinder': '圆柱', 'fx.preset.cone': '圆锥', 'fx.preset.helix': '螺旋线',
    'fx.preset.plane': '平面网格', 'fx.preset.circle': '圆周', 'fx.preset.disc': '圆盘', 'fx.preset.star': '星形',
    'fx.preset.rising_smoke': '循环上升烟雾',
    'fx.param.amp': '振幅', 'fx.param.freq': '频率', 'fx.param.wid': '宽度', 'fx.param.rad': '半径',
    'fx.param.edge': '边长', 'fx.param.major': '大半径', 'fx.param.minor': '管半径', 'fx.param.m': '密度',
    'fx.param.k': '圆环密度', 'fx.param.h': '高度', 'fx.param.cr': '顶/底密度', 'fx.param.spd': '上升速度',
    'fx.param.w': '宽', 'fx.param.d': '深', 'fx.param.diskR': '半径',
    // —— 贴图编辑器 ——
    'tex.tool.select': '矩形选区', 'tex.tool.move': '移动选区（在选区内拖动移动内容）',
    'tex.tool.pencil': '铅笔', 'tex.tool.bucket': '油漆桶', 'tex.tool.picker': '滴管（按住 Alt 临时切换）',
    'tex.upload': '上传贴图', 'tex.export': '导出',
    'tex.selectHint': '选中对象以编辑贴图 / UV',
    'tex.namePrompt': '贴图名称', 'tex.renameTitle': '重命名贴图', 'tex.newName': '新名称',
    'tex.deleteTitle': '删除贴图', 'tex.resize': '修改大小', 'tex.resizeTitle': '修改大小 · {0}',
    'tex.width': '宽', 'tex.height': '高', 'tex.texLabel': '贴图 ', 'tex.none': '无', 'tex.uvMode': 'UV 模式 ',
    'tex.px': '像素', 'tex.multiply': '乘以', 'tex.perSec': '/ 秒', 'tex.maxFrames': '最大帧数',
    'tex.maxFramesHint': '0 或 1 = 自动（按 UV 步长算满）；>1 = 最大上限',
    'tex.texSize': '贴图大小', 'tex.uvStart': 'UV 起点', 'tex.uvSize': 'UV 大小', 'tex.uvStep': 'UV 步长',
    'tex.fps': '帧率',
    'uv.mode.static': '静态', 'uv.mode.fill': '填充', 'uv.mode.animated': '动画',
    // —— 时间轴 ——
    'timeline.resizeTitle': '拖拽调整时间轴模块高度', 'timeline.speed': '速度', 'timeline.loop': '循环',
    'timeline.easing': '缓动函数', 'timeline.play': '▶ 播放', 'timeline.pause': '⏸ 暂停',
    // —— 粒子列表 / 树 ——
    'tree.addParticle': '添加粒子',
    'tree.edit': '编辑',
    'tree.hint': '提示', 'tree.selectParticlesFirst': '请先选中粒子', 'tree.derivedNoGroup': '派生粒子不可建立普通组',
    'tree.empty': '暂无粒子，请使用右侧工具绘制', 'tree.dblclickRename': '双击重命名',
    'tree.trackCount': '{0} 轨道', 'tree.deleteParticle': '删除粒子', 'tree.addKfHint': '添加关键帧（当前时间）',
    'tree.memberCount': '{0} 成员', 'tree.deleteGroup': '删除组及其粒子',
    'tree.particleListCount': '粒子列表 ({0})', 'tree.fxParticleCount': '{0} 粒子', 'tree.deleteFx': '删除函数对象',
    'tree.deleteKf': '删除关键帧', 'tree.editKf': '编辑关键帧 · {0} {1}', 'tree.editVarKf': '编辑变量关键帧 · {0}', 'tree.time': '时间', 'tree.value': '值',
    'tree.easingLabel': '缓动',
    'draw.countLabel': '粒子数量',
    // —— 文件流程 ——
    'newProject.title': '新建项目', 'newProject.name': '项目名称',
    'confirm.unsavedTitle': '未保存的更改', 'confirm.unsavedMsg': '当前工程有未保存的修改。',
    'confirm.discard': '不保存', 'confirm.saveAnd': '保存并',
    'filePicker.project': 'ParticleDrawing 工程', 'filePicker.projectFile': '工程文件',
    'filePicker.oldVersionTitle': '工程版本过旧', 'filePicker.oldVersionMsg': '当前版本不支持旧版工程，请新建工程。',
    'filePicker.playback': 'ParticleDrawing 播放文件', 'filePicker.playbackFile': '播放文件 (.pdrawc)',
    'import.hint': '选择图片或 GIF，按像素生成粒子并自动建组（GIF 取第一帧）',
    'import.image': '导入图片', 'import.gif': '导入动图',
    'import.resolution': '分辨率（横向粒子数）', 'import.button': '选择图片 / GIF',
    'import.resolutionTitle': '导入分辨率', 'import.cols': '横向粒子数', 'import.rows': '纵向粒子数',
    'import.particleCount': '粒子数：{0}',
    'import.tooMany': '粒子数超过上限 {0}，请降低分辨率', 'import.empty': '图片中没有不透明像素',
    'import.gifUnsupported': '当前浏览器不支持 GIF 逐帧解析，请使用 Chrome/Edge', 'import.tooComplex': 'GIF 颜色变化过多（超过 {0} 个关键帧），请降低分辨率',
    'alert.importFailed': '导入失败',
    'alert.cryptoUnsupported': '当前浏览器不支持 Ed25519 签名，请升级浏览器后再导出',
    'alert.exportKeyMissing': '工程缺少签名私钥，请先保存工程后再导出',
    // —— 关于 ——
    'about.title': '关于 ParticleDrawing',
    'about.desc': 'ParticleDrawing 粒子动画编辑器 — 用于创作 .pdraw 动画并在 Minecraft 中播放。',
    'about.developer': '开发者',
    // —— 缓动编辑器 ——
    'easing.editTitle': '编辑缓动函数', 'easing.editorTitle': '缓动函数编辑器', 'easing.presets': '预设…',
    'easing.none': '无缓动',
    // —— 悬浮窗 ——
    'fwin.minimize': '最小化',
    // —— 默认命名 ——
    'default.particleName': '粒子', 'default.groupName': '组', 'default.cameraName': '摄像机',
    // —— 摄像机 ——
    'tool.camera': '新建摄像机（点按放置）',
    'cam.default': '默认',
    // —— 贴图提示 ——
    'alert.uploadFailed': '上传失败', 'alert.texTooBig': '贴图超过 5MB 上限', 'alert.pngOnly': '仅支持 PNG 格式',
    'alert.pngParseFail': '无法解析该 PNG 文件', 'alert.exportFailed': '导出失败',
    'alert.noTexture': '当前无贴图，请先新建或上传', 'alert.pngGenFail': '无法生成 PNG',
    'alert.renameFailed': '重命名失败', 'alert.nameEmpty': '名称不能为空', 'alert.nameTaken': '已存在同名对象「{0}」',
    'alert.texExists': '已存在同名贴图「{0}」',
    'alert.deleteTexConfirm': '确定删除「{0}」吗？\n引用它的对象将恢复为无贴图。',
    // —— 表达式错误 ——
    'err.dotNeedsVec': 'dot 需要向量', 'err.crossNeedsVec': 'cross 需要向量', 'err.normNeedsVec': 'norm 需要向量',
    'err.rotAxisNeedsVec': 'rotAxis 需要向量轴', 'err.negType': '一元负号类型不支持',
    'err.opAdd': '运算符 + 类型不匹配', 'err.opSub': '运算符 - 类型不匹配', 'err.opMul': '运算符 * 类型不匹配',
    'err.opDiv': '运算符 / 类型不匹配', 'err.opMod': '运算符 % 仅支持标量', 'err.opPow': '运算符 ^ 仅支持标量',
    'err.unknownOp': '未知运算符: {0}', 'err.compNeedsVec': '分量访问需要向量', 'err.unknownVar': '未知变量: {0}',
    'err.propScalar': '属性 {0} 需要标量值', 'err.missingEq': '表达式缺少 = : {0}',
    'err.assignCount': '赋值数量不匹配', 'err.assignCount2': '赋值数量不匹配: {0}',
    'err.unknownExprNode': '未知表达式节点: {0}', 'err.unknownStmt': '未知语句块: {0}',
    'err.exprNeed': '表达式缺少 {0} : {1}', 'err.exprEnd': '表达式意外结束',
    'err.funcNoParen': '函数缺少括号: {0}', 'err.unexpectedTok': '意外符号: {0}',
    'err.exprExtra': '表达式有多余内容: {0}', 'err.stmtMissingEq': '语句缺少 = : {0}',
    'err.stmtNeedParen': '语句缺少括号', 'err.stmtNeedBrace': '语句缺少花括号',
    'err.unknownPack': '无法识别的打包赋值: {0}', 'err.unknownUnpack': '无法识别的向量拆包: {0}',
    'err.glowBinary': '发光赋值只能是 0 或 1: {0}',
    'err.varCycle': '变量循环引用: {0}', 'err.varReserved': '变量名 {0} 是属性保留字，请换名',
    // —— 拼图 UI ——
    'blk.title': '拼图代码块', 'blk.palette': '积木面板', 'blk.scene': '场景', 'blk.code': '代码',
    'blk.lensHint': '拖动到拼图上查看含义',
    'blk.openFailTitle': '无法用拼图打开', 'blk.parseFail': '代码解析失败\n{0}\n\n请先在文本视图修正代码。',
    'blk.varExprErrTitle': '变量表达式错误', 'blk.varExprErr': '变量 {0} 的表达式解析失败：{1}',
    'blk.start': '粒子每帧', 'blk.setup': '初始化', 'blk.fragment': '碎片', 'blk.block': '积木',
    'blk.addParam': '添加参数', 'blk.funcParam': '函数参数 {0}',
    'blk.sampleCount': '采样数', 'blk.varHasKf': '{0}（有关键帧，由时间轴驱动）',
    'blk.attrRefHint': '拖入表达式以引用属性 {0}',
    'blk.clickSwapComp': '点击切换分量', 'blk.addTerm': '+ 项', 'blk.addTermHint': '拖入数值或运算符以追加',
    'blk.glowOn': '发光:开', 'blk.glowOff': '发光:关', 'blk.colorPicker': '取色器', 'blk.customFunc': '自定义函数',
    'blk.chain': '算式', 'blk.chainDesc': '动态算式（可追加项）',
    'blk.constNum': '常量数值', 'blk.var': '变量', 'blk.op': '运算符',
    'blk.comp': '.分量', 'blk.compDesc': '取向量的 x/y/z 分量', 'blk.neg': '取负',
    'blk.ternaryDesc': '三元运算（条件 ? 真值 : 假值）', 'blk.notDesc': '逻辑非',
    'blk.arrayDesc': '数组字面量', 'blk.indexDesc': '数组下标访问', 'blk.methodDesc': '数组方法调用',
    'blk.method.push.desc': '向数组末尾追加一个元素',
    'blk.method.insert.desc': '在指定下标处插入一个元素',
    'blk.method.remove.desc': '删除指定下标的元素',
    'blk.method.slice.desc': '截取从起始下标开始的若干元素',
    'blk.method.size.desc': '获取数组长度',
    'blk.method.find.desc': '查找元素并返回其下标',
    'blk.method.includes.desc': '判断数组是否包含某元素',
    'blk.method.sort.desc': '对数组元素排序',
    'blk.method.unique.desc': '对数组元素去重',
    'blk.method.reverse.desc': '反转数组元素顺序',
    'blk.piInfo': '圆周率 π ≈ 3.14159', 'blk.eInfo': '自然常数 e ≈ 2.71828',
    // —— 拼图：类型 / 内置变量 / 调色板 / 运算符 / 参数 ——
    'blk.type.scalar': '数字', 'blk.type.vec': '向量', 'blk.type.mat': '矩阵', 'blk.type.any': '任意',
    'blk.stmt.if': '如果', 'blk.stmt.while': '当循环', 'blk.stmt.for': '计数循环', 'blk.stmt.do': '直到循环', 'blk.stmt.func': '函数', 'blk.stmt.global': '全局变量', 'blk.stmt.static': '静态变量', 'blk.stmt.break': '跳出循环', 'blk.stmt.continue': '继续循环', 'blk.stmt.return': '返回', 'blk.stmt.else': '否则', 'blk.stmt.else_if': '否则如果', 'blk.stmt.else.desc': '为如果块添加否则分支', 'blk.stmt.else_if.desc': '为如果块添加否则如果分支', 'blk.stmt.setup.desc': '对象初始化时执行一次', 'blk.stmt.process.desc': '每个粒子每帧执行', 'blk.stmt.func.desc': '定义顶层函数（可递归，供 setup/process 调用）', 'blk.repeatTimes': '次',
    'blk.var.i': '粒子序号（0 ~ n-1）', 'blk.var.n': '采样数（粒子总数）', 'blk.var.t': '当前时间（tick）',
    'blk.var.index': '当前粒子序号（this.index）', 'blk.var.count': '粒子总数（this.count）', 'blk.var.time': '当前时间（this.time）',
    'blk.var.delta': '帧间隔（this.delta）', 'blk.var.duration': '动画总时长（this.duration）', 'blk.var.life': '寿命 tick（this.life）', 'blk.var.uv': '网格 UV（this.uv）',
    'blk.pal.start': '起始块', 'blk.pal.funcs': '自定义函数', 'blk.pal.pos': '位置 / 速度', 'blk.pal.color': '颜色', 'blk.pal.appearance': '外观', 'blk.pal.logic': '逻辑', 'blk.pal.math': '数学',
    'blk.pal.vec': '向量', 'blk.pal.mat': '矩阵', 'blk.pal.var': '变量', 'blk.pal.const': '常量',
    'blk.pal.props': '属性', 'blk.pal.array': '数组',
    // —— 拼图：合并块下拉 ——
    'blk.dd.trig': '三角函数', 'blk.dd.trig.desc': '正弦 / 余弦 / 正切等三角函数',
    'blk.dd.numeric': '数值操作', 'blk.dd.numeric.desc': '开方 / 绝对值 / 取整 / 对数等数值操作',
    'blk.dd.clamp': '限制', 'blk.dd.clamp.desc': '取最小值 / 最大值 / 限制在区间内',
    'blk.dd.array': '数组操作', 'blk.dd.array.desc': '追加 / 插入 / 删除 / 查找 / 排序等数组操作',
    'blk.dd.context': '上下文', 'blk.dd.context.desc': '粒子序号 / 时间 / 寿命等只读上下文值',
    'blk.externalVars': '外部变量',
    'blk.bool.true': '真', 'blk.bool.false': '假',
    // —— 拼图：上下文短显示名 ——
    'blk.ctx.index': '索引', 'blk.ctx.count': '总数', 'blk.ctx.time': '时间',
    'blk.ctx.delta': '帧时间', 'blk.ctx.duration': '总时长', 'blk.ctx.life': '寿命',
    'blk.ctx.uvx': '网格U', 'blk.ctx.uvy': '网格V',
    // —— 拼图：数组方法短显示名 ——
    'blk.method.push.label': '追加', 'blk.method.insert.label': '插入', 'blk.method.remove.label': '删除',
    'blk.method.slice.label': '截取', 'blk.method.size.label': '长度', 'blk.method.find.label': '查找',
    'blk.method.includes.label': '包含', 'blk.method.sort.label': '排序', 'blk.method.unique.label': '去重',
    'blk.method.reverse.label': '反转',
    'blk.method.push.phrase': '追加内容', 'blk.method.insert.phrase': '插入内容', 'blk.method.remove.phrase': '删除',
    'blk.method.slice.phrase': '截取', 'blk.method.size.phrase': '长度', 'blk.method.find.phrase': '查找',
    'blk.method.includes.phrase': '包含', 'blk.method.sort.phrase': '排序', 'blk.method.unique.phrase': '去重',
    'blk.method.reverse.phrase': '反转', 'blk.arg.array': '数组',
    'blk.op.add': '加', 'blk.op.sub': '减', 'blk.op.mul': '乘', 'blk.op.div': '除', 'blk.op.mod': '取余', 'blk.op.pow': '幂',
    'blk.op.eq': '等于', 'blk.op.ne': '不等于', 'blk.op.lt': '小于', 'blk.op.le': '小于等于', 'blk.op.gt': '大于', 'blk.op.ge': '大于等于', 'blk.op.and': '且', 'blk.op.or': '或',
    'blk.arg.angle': '角度', 'blk.arg.value': '值', 'blk.arg.base': '底数', 'blk.arg.exp': '指数',
    'blk.arg.lo': '下界', 'blk.arg.hi': '上界', 'blk.arg.edge': '边界', 'blk.arg.mod': '模',
    'blk.arg.seed': '种子', 'blk.arg.vec': '向量', 'blk.arg.axis': '轴', 'blk.arg.radius': '半径',
    'blk.slot.scale': '缩放', 'blk.slot.light': '光照',
    // —— 拼图：语句块 ——
    'blk.stmt.pos.label': '位置', 'blk.stmt.pos.desc': '设置 this.position = [x, y, z]',
    'blk.stmt.pos_vec.label': '位置', 'blk.stmt.pos_vec.desc': '用向量设置 this.position',
    'blk.stmt.vel.label': '速度', 'blk.stmt.vel.desc': '设置 this.velocity = [vx, vy, vz]',
    'blk.stmt.vel_vec.label': '速度', 'blk.stmt.vel_vec.desc': '用向量设置 this.velocity',
    'blk.stmt.col.label': '颜色', 'blk.stmt.col.desc': '设置 this.color = [r, g, b, a]',
    'blk.stmt.scl.label': '缩放', 'blk.stmt.scl.desc': '设置 this.scale',
    'blk.stmt.glow.label': '发光', 'blk.stmt.glow.desc': '设置 this.glow',
    'blk.stmt.light.label': '光照等级', 'blk.stmt.light.desc': '设置 this.light',
    'blk.stmt.attr.label': '设置属性', 'blk.stmt.attr.desc': '设置 this 分量（position.x/color.r/…）',
    'blk.stmt.set.label': '临时变量', 'blk.stmt.set.desc': '定义临时变量并赋值',
    'blk.stmt.comment.label': '注释', 'blk.stmt.comment.desc': '添加注释（不执行）',
    'blk.stmt.repeat.label': '重复执行', 'blk.stmt.repeat.desc': '无限重复执行内部积木',
    'blk.stmt.repeat_n.label': '重复执行', 'blk.stmt.repeat_n.desc': '重复执行内部积木指定次数',
    'blk.stmt.repeat_until.label': '重复执行直到', 'blk.stmt.repeat_until.desc': '重复执行直到条件为真',
    // —— 拼图：函数说明 ——
    'blk.func.sin.desc': '正弦函数', 'blk.func.cos.desc': '余弦函数', 'blk.func.tan.desc': '正切函数',
    'blk.func.asin.desc': '反正弦函数', 'blk.func.acos.desc': '反余弦函数', 'blk.func.atan.desc': '反正切函数',
    'blk.func.atan2.desc': '反正切函数', 'blk.func.sqrt.desc': '平方根', 'blk.func.abs.desc': '绝对值',
    'blk.func.sign.desc': '符号函数（正 1 / 负 -1 / 零 0）', 'blk.func.exp.desc': '指数函数 e^x',
    'blk.func.log.desc': '以 10 为底的常用对数', 'blk.func.ln.desc': '以 e 为底的自然对数',
    'blk.func.floor.desc': '向下取整', 'blk.func.ceil.desc': '向上取整', 'blk.func.round.desc': '四舍五入',
    'blk.func.fract.desc': '取小数部分', 'blk.func.pow.desc': '幂运算',
    'blk.func.min.desc': '取两者较小值', 'blk.func.max.desc': '取两者较大值',
    'blk.func.clamp.desc': '把值限制在区间内', 'blk.func.lerp.desc': '线性插值 a→b',
    'blk.func.step.desc': '阶跃（x≥边界返回 1，否则 0）', 'blk.func.smoothstep.desc': '平滑阶跃插值',
    'blk.func.mod.desc': '取模（GLSL 语义）', 'blk.func.random.desc': '随机数（0 到 1 之间）',
    'blk.func.rand.desc': '固定伪随机（同一种子恒返回相同的 [0,1) 值）',
    'blk.func.vec.desc': '由分量构造向量', 'blk.func.dot.desc': '向量点积', 'blk.func.cross.desc': '向量叉积',
    'blk.func.len.desc': '向量长度', 'blk.func.norm.desc': '向量归一化',
    'blk.func.rotX.desc': '绕 X 轴旋转矩阵', 'blk.func.rotY.desc': '绕 Y 轴旋转矩阵', 'blk.func.rotZ.desc': '绕 Z 轴旋转矩阵',
    'blk.func.rotAxis.desc': '绕任意轴旋转矩阵', 'blk.func.polar.desc': '极坐标转向量',
    'blk.func.sphere.desc': '球坐标转向量', 'blk.func.torus.desc': '环面坐标转向量',
  },
  en: {
    // —— 通用 ——
    'common.ok': 'OK', 'common.cancel': 'Cancel', 'common.delete': 'Delete', 'common.rename': 'Rename',
    'common.new': 'New', 'common.open': 'Open', 'common.save': 'Save', 'common.undo': 'Undo', 'common.redo': 'Redo',
    'common.close': 'Close', 'common.color': 'Color',
    // —— 菜单 ——
    'menu.file': 'File', 'menu.import': 'Import', 'menu.edit': 'Edit', 'menu.lang': 'Language', 'menu.about': 'About',
    'menu.openEllipsis': 'Open…', 'menu.saveAs': 'Save As…', 'menu.exportAnim': 'Export Animation…', 'menu.clear': 'Clear',
    'menu.selectAll': 'Select All', 'menu.deleteSelected': 'Delete Selected', 'menu.group': 'Group',
    // —— 面板 / 选项卡 ——
    'panel.particleList': 'Particle List',
    'mobile.panels': 'Properties / FX / Texture', 'mobile.timeline': 'Timeline',
    'tab.props': 'Properties', 'tab.fx': 'Function Object', 'tab.texture': 'Texture / UV', 'tab.import': 'Import',
    // —— 场景工具栏 ——
    'tool.select': 'Select (Box)', 'tool.move': 'Move', 'tool.rotate': 'Rotate',
    'tool.rotateSpin': 'Rotate (Spin mode, press R to toggle)', 'tool.rotateOrbit': 'Rotate (Orbit mode, press R to toggle)',
    'rotMode.spin': 'S', 'rotMode.orbit': 'O',
    'spinSpace.world': 'W', 'spinSpace.local': 'L', 'spinSpace.hint': 'W: World coordinate system\nL: Local coordinate system',
    'rotSpace.world': 'W', 'rotSpace.local': 'L', 'rotSpace.hint': 'W: World coordinate system\nL: Local coordinate system',
    'tool.pencil': 'Pencil (Click to Place)', 'tool.line': 'Line', 'tool.circle': 'Circle', 'tool.rect': 'Rectangle', 'tool.freehand': 'Freehand',
    // —— 属性面板 ——
    'props.opacity': 'Opacity', 'props.scale': 'Scale', 'props.glow': 'Glow', 'props.light': 'Light Level',
    'props.life': 'Life (tick)', 'props.lifeHint': '-1 or empty = infinite (lives until animation ends)',
    'prop.pos': 'Position', 'prop.target': 'Target', 'prop.rot': 'Orbit', 'prop.rotCam': 'Rotate', 'prop.spin': 'Spin', 'prop.center': 'Orbit Center', 'prop.vel': 'Velocity', 'prop.col': 'Color', 'prop.scl': 'Scale', 'prop.fov': 'FOV',
    // —— 函数对象 ——
    'fx.addPresetTitle': 'Create function object from preset', 'fx.noSelection': 'Select a function object to edit its properties',
    'fx.exprError': 'Expression Error', 'fx.sampleCount': 'Sample Count ', 'fx.center': 'Center ',
    'fx.noVars': 'No variables',
    'fx.duration': 'Duration ', 'fx.interval': ' Interval ', 'fx.codeBlock': 'Code Block', 'fx.puzzle': '🧩 Puzzle',
    'fx.setupBlock': 'Init', 'fx.processBlock': 'Per Particle', 'fx.funcsBlock': 'Top-level Functions', 'fx.seed': 'Seed ',
    'fx.fastMath': 'Fast math approximation',
    'fx.puzzleHint': 'Edit code as puzzle blocks', 'fx.varList': 'Variables', 'fx.addVar': 'Add variable',
    'fx.varListHint': 'Values driven by the timeline',
    'fx.collapseKf': 'Collapse keyframes', 'fx.expandKf': 'Expand keyframes',
    'fx.kfSyncedHint': 'Has keyframes: value is driven by the timeline (remove all keyframes to edit the expression)',
    'fx.varNameError': 'Invalid Variable Name', 'fx.varNameReserved': 'Variable name {0} is a reserved attribute name',
    'fx.varNameInvalid': 'Variable name {0} is invalid (must start with a letter or underscore and contain only letters, digits, and underscores)', 'fx.varNameExists': 'Variable name {0} already exists',
    'fx.kfCountHint': 'Keyframe count (click ▸ to expand)', 'fx.addKf': '+ Keyframe',
    'fx.defaultName': 'Function Object',
    'fx.preset.blank': 'Empty', 'fx.preset.sin': 'SIN Function', 'fx.preset.sphere': 'Sphere', 'fx.preset.cube': 'Cube',
    'fx.preset.torus': 'Torus', 'fx.preset.cylinder': 'Cylinder', 'fx.preset.cone': 'Cone', 'fx.preset.helix': 'Helix',
    'fx.preset.plane': 'Plane Grid', 'fx.preset.circle': 'Circle', 'fx.preset.disc': 'Disc', 'fx.preset.star': 'Star',
    'fx.preset.rising_smoke': 'Rising Smoke',
    'fx.param.amp': 'Amplitude', 'fx.param.freq': 'Frequency', 'fx.param.wid': 'Width', 'fx.param.rad': 'Radius',
    'fx.param.edge': 'Edge', 'fx.param.major': 'Major R', 'fx.param.minor': 'Tube R', 'fx.param.m': 'Density',
    'fx.param.k': 'Ring Density', 'fx.param.h': 'Height', 'fx.param.cr': 'Top/Bottom Density', 'fx.param.spd': 'Rise Speed',
    'fx.param.w': 'Width', 'fx.param.d': 'Depth', 'fx.param.diskR': 'Radius',
    // —— 贴图编辑器 ——
    'tex.tool.select': 'Rectangle Selection', 'tex.tool.move': 'Move Selection (drag inside to move content)',
    'tex.tool.pencil': 'Pencil', 'tex.tool.bucket': 'Bucket', 'tex.tool.picker': 'Eyedropper (hold Alt)',
    'tex.upload': 'Upload Texture', 'tex.export': 'Export',
    'tex.selectHint': 'Select an object to edit texture / UV',
    'tex.namePrompt': 'Texture Name', 'tex.renameTitle': 'Rename Texture', 'tex.newName': 'New Name',
    'tex.deleteTitle': 'Delete Texture', 'tex.resize': 'Resize', 'tex.resizeTitle': 'Resize · {0}',
    'tex.width': 'Width', 'tex.height': 'Height', 'tex.texLabel': 'Texture ', 'tex.none': 'None', 'tex.uvMode': 'UV Mode ',
    'tex.px': 'px', 'tex.multiply': 'multiply', 'tex.perSec': '/ sec', 'tex.maxFrames': 'Max Frames',
    'tex.maxFramesHint': '0 or 1 = auto (fill by UV step); >1 = max limit',
    'tex.texSize': 'Texture Size', 'tex.uvStart': 'UV Start', 'tex.uvSize': 'UV Size', 'tex.uvStep': 'UV Step',
    'tex.fps': 'Frame Rate',
    'uv.mode.static': 'Static', 'uv.mode.fill': 'Fill', 'uv.mode.animated': 'Animated',
    // —— 时间轴 ——
    'timeline.resizeTitle': 'Drag to resize timeline module', 'timeline.speed': 'Speed', 'timeline.loop': 'Loop',
    'timeline.easing': 'Easing', 'timeline.play': '▶ Play', 'timeline.pause': '⏸ Pause',
    // —— 粒子列表 / 树 ——
    'tree.addParticle': 'Add Particle',
    'tree.edit': 'Edit',
    'tree.hint': 'Notice', 'tree.selectParticlesFirst': 'Please select particles first', 'tree.derivedNoGroup': 'Derived particles cannot form a regular group',
    'tree.empty': 'No particles yet. Use the tools on the right to draw.',
    'tree.dblclickRename': 'Double-click to rename',
    'tree.trackCount': '{0} tracks', 'tree.deleteParticle': 'Delete Particle', 'tree.addKfHint': 'Add keyframe (at current time)',
    'tree.memberCount': '{0} members', 'tree.deleteGroup': 'Delete Group and Its Particles',
    'tree.particleListCount': 'Particle List ({0})', 'tree.fxParticleCount': '{0} particles', 'tree.deleteFx': 'Delete Function Object',
    'tree.deleteKf': 'Delete Keyframe', 'tree.editKf': 'Edit Keyframe · {0} {1}', 'tree.editVarKf': 'Edit Variable Keyframe · {0}', 'tree.time': 'Time', 'tree.value': 'Value',
    'tree.easingLabel': 'Easing',
    'draw.countLabel': 'Particle Count',
    // —— 文件流程 ——
    'newProject.title': 'New Project', 'newProject.name': 'Project Name',
    'confirm.unsavedTitle': 'Unsaved Changes', 'confirm.unsavedMsg': 'The current project has unsaved changes.',
    'confirm.discard': "Don't Save", 'confirm.saveAnd': 'Save & ',
    'filePicker.project': 'ParticleDrawing Project', 'filePicker.projectFile': 'Project File',
    'filePicker.oldVersionTitle': 'Project Version Too Old', 'filePicker.oldVersionMsg': 'This version does not support old projects. Please create a new project.',
    'filePicker.playback': 'ParticleDrawing Playback File', 'filePicker.playbackFile': 'Playback File (.pdrawc)',
    'import.hint': 'Choose an image or GIF to generate particles by pixels and auto-group them (GIF uses the first frame)',
    'import.image': 'Import Image', 'import.gif': 'Import GIF',
    'import.resolution': 'Resolution (particles across)', 'import.button': 'Choose Image / GIF',
    'import.resolutionTitle': 'Import Resolution', 'import.cols': 'Horizontal particles', 'import.rows': 'Vertical particles',
    'import.particleCount': 'Particle count: {0}',
    'import.tooMany': 'Particle count exceeds the limit of {0}. Lower the resolution.',
    'import.empty': 'No opaque pixels found in the image',
    'import.gifUnsupported': 'GIF frame decoding is not supported in this browser. Use Chrome or Edge.',
    'import.tooComplex': 'Too many GIF color changes (more than {0} keyframes). Lower the resolution.',
    'alert.importFailed': 'Import Failed',
    'alert.cryptoUnsupported': 'This browser does not support Ed25519 signing. Please upgrade your browser before exporting.',
    'alert.exportKeyMissing': 'The project has no signing key. Save the project first, then export.',
    // —— 关于 ——
    'about.title': 'About ParticleDrawing',
    'about.desc': 'ParticleDrawing Particle Animation Editor — create .pdraw animations and play them in Minecraft.',
    'about.developer': 'Developer',
    // —— 缓动编辑器 ——
    'easing.editTitle': 'Edit Easing', 'easing.editorTitle': 'Easing Editor', 'easing.presets': 'Presets…',
    'easing.none': 'None',
    // —— 悬浮窗 ——
    'fwin.minimize': 'Minimize',
    // —— 默认命名 ——
    'default.particleName': 'Particle', 'default.groupName': 'Group', 'default.cameraName': 'Camera',
    // —— 摄像机 ——
    'tool.camera': 'New camera (click to place)',
    'cam.default': 'Default',
    // —— 贴图提示 ——
    'alert.uploadFailed': 'Upload Failed', 'alert.texTooBig': 'Texture exceeds the 5MB limit', 'alert.pngOnly': 'Only PNG format is supported',
    'alert.pngParseFail': 'Unable to parse this PNG file', 'alert.exportFailed': 'Export Failed',
    'alert.noTexture': 'No texture available. Create or upload one first.', 'alert.pngGenFail': 'Unable to generate PNG',
    'alert.renameFailed': 'Rename Failed', 'alert.nameEmpty': 'Name cannot be empty', 'alert.nameTaken': 'An object named "{0}" already exists',
    'alert.texExists': 'A texture named "{0}" already exists',
    'alert.deleteTexConfirm': 'Delete "{0}"?\nObjects referencing it will revert to no texture.',
    // —— 表达式错误 ——
    'err.dotNeedsVec': 'dot requires a vector', 'err.crossNeedsVec': 'cross requires a vector', 'err.normNeedsVec': 'norm requires a vector',
    'err.rotAxisNeedsVec': 'rotAxis requires a vector axis', 'err.negType': 'unary minus not supported for this type',
    'err.opAdd': 'operator + type mismatch', 'err.opSub': 'operator - type mismatch', 'err.opMul': 'operator * type mismatch',
    'err.opDiv': 'operator / type mismatch', 'err.opMod': 'operator % only supports scalars', 'err.opPow': 'operator ^ only supports scalars',
    'err.unknownOp': 'unknown operator: {0}', 'err.compNeedsVec': 'component access requires a vector', 'err.unknownVar': 'unknown variable: {0}',
    'err.propScalar': 'property {0} requires a scalar value', 'err.missingEq': 'expression missing = : {0}',
    'err.assignCount': 'assignment count mismatch', 'err.assignCount2': 'assignment count mismatch: {0}',
    'err.unknownExprNode': 'unknown expression node: {0}', 'err.unknownStmt': 'unknown statement block: {0}',
    'err.exprNeed': 'expression missing {0} : {1}', 'err.exprEnd': 'unexpected end of expression',
    'err.funcNoParen': 'function missing parentheses: {0}', 'err.unexpectedTok': 'unexpected token: {0}',
    'err.exprExtra': 'extra content in expression: {0}', 'err.stmtMissingEq': 'statement missing = : {0}',
    'err.stmtNeedParen': 'statement missing parenthesis', 'err.stmtNeedBrace': 'statement missing brace',
    'err.unknownPack': 'unrecognized packed assignment: {0}', 'err.unknownUnpack': 'unrecognized vector unpack: {0}',
    'err.glowBinary': 'glow assignment must be 0 or 1: {0}',
    'err.varCycle': 'variable circular reference: {0}', 'err.varReserved': 'Variable name {0} is a reserved attribute name, please rename',
    // —— 拼图 UI ——
    'blk.title': 'Puzzle Code Blocks', 'blk.palette': 'Blocks', 'blk.scene': 'Scene', 'blk.code': 'Code',
    'blk.lensHint': 'Drag onto a block to see its meaning',
    'blk.openFailTitle': 'Cannot Open in Puzzle View', 'blk.parseFail': 'Failed to parse code\n{0}\n\nPlease fix the code in text view first.',
    'blk.varExprErrTitle': 'Variable Expression Error', 'blk.varExprErr': 'Failed to parse expression of variable {0}: {1}',
    'blk.start': 'Per Particle', 'blk.setup': 'Init', 'blk.fragment': 'Fragment', 'blk.block': 'Block',
    'blk.addParam': 'Add parameter', 'blk.funcParam': 'Function parameter {0}',
    'blk.sampleCount': 'Sample Count', 'blk.varHasKf': '{0} (has keyframes, driven by the timeline)',
    'blk.attrRefHint': 'Drop an expression to reference property {0}',
    'blk.clickSwapComp': 'Click to cycle component', 'blk.addTerm': '+ Term', 'blk.addTermHint': 'Drop a number or operator to append',
    'blk.glowOn': 'Glow: On', 'blk.glowOff': 'Glow: Off', 'blk.colorPicker': 'Color Picker', 'blk.customFunc': 'Custom function',
    'blk.chain': 'Expression', 'blk.chainDesc': 'Dynamic expression (appendable)',
    'blk.constNum': 'Constant number', 'blk.var': 'Variable', 'blk.op': 'Operator',
    'blk.comp': '.Component', 'blk.compDesc': 'Take x/y/z component of a vector', 'blk.neg': 'Negate',
    'blk.ternaryDesc': 'Ternary (cond ? then : else)', 'blk.notDesc': 'Logical NOT',
    'blk.arrayDesc': 'Array literal', 'blk.indexDesc': 'Array indexing', 'blk.methodDesc': 'Array method call',
    'blk.method.push.desc': 'Append an element to the end of the array',
    'blk.method.insert.desc': 'Insert an element at the given index',
    'blk.method.remove.desc': 'Remove the element at the given index',
    'blk.method.slice.desc': 'Take a number of elements starting at an index',
    'blk.method.size.desc': 'Get the array length',
    'blk.method.find.desc': 'Find an element and return its index',
    'blk.method.includes.desc': 'Check whether the array contains an element',
    'blk.method.sort.desc': 'Sort the array elements',
    'blk.method.unique.desc': 'Remove duplicate array elements',
    'blk.method.reverse.desc': 'Reverse the order of array elements',
    'blk.piInfo': 'Pi π ≈ 3.14159', 'blk.eInfo': 'Euler\'s number e ≈ 2.71828',
    // —— 拼图：类型 / 内置变量 / 调色板 / 运算符 / 参数 ——
    'blk.type.scalar': 'Number', 'blk.type.vec': 'Vector', 'blk.type.mat': 'Matrix', 'blk.type.any': 'Any',
    'blk.stmt.if': 'If', 'blk.stmt.while': 'While', 'blk.stmt.for': 'For', 'blk.stmt.do': 'Do-while', 'blk.stmt.func': 'Function', 'blk.stmt.global': 'Global', 'blk.stmt.static': 'Static', 'blk.stmt.break': 'Break', 'blk.stmt.continue': 'Continue', 'blk.stmt.return': 'Return', 'blk.stmt.else': 'Else', 'blk.stmt.else_if': 'Else If', 'blk.stmt.else.desc': 'Add an else branch to an if block', 'blk.stmt.else_if.desc': 'Add an else-if branch to an if block', 'blk.stmt.setup.desc': 'Runs once during object init', 'blk.stmt.process.desc': 'Runs for every particle every frame', 'blk.stmt.func.desc': 'Defines a top-level function (recursive, callable from setup/process)', 'blk.repeatTimes': 'times',
    'blk.var.i': 'Particle index (0 ~ n-1)', 'blk.var.n': 'Sample count (total particles)', 'blk.var.t': 'Current time (tick)',
    'blk.var.index': 'Current particle index (this.index)', 'blk.var.count': 'Total particles (this.count)', 'blk.var.time': 'Current time (this.time)',
    'blk.var.delta': 'Frame delta (this.delta)', 'blk.var.duration': 'Total animation duration (this.duration)', 'blk.var.life': 'Life ticks (this.life)', 'blk.var.uv': 'Grid UV (this.uv)',
    'blk.pal.start': 'Hat Blocks', 'blk.pal.funcs': 'Functions', 'blk.pal.pos': 'Position / Velocity', 'blk.pal.color': 'Color', 'blk.pal.appearance': 'Appearance', 'blk.pal.logic': 'Logic', 'blk.pal.math': 'Math',
    'blk.pal.vec': 'Vector', 'blk.pal.mat': 'Matrix', 'blk.pal.var': 'Variable', 'blk.pal.const': 'Constants',
    'blk.pal.props': 'Properties', 'blk.pal.array': 'Array',
    // —— 拼图：合并块下拉 ——
    'blk.dd.trig': 'Trigonometry', 'blk.dd.trig.desc': 'Sin / cos / tan and inverse trig functions',
    'blk.dd.numeric': 'Numeric', 'blk.dd.numeric.desc': 'Root, absolute value, rounding, logarithms and more',
    'blk.dd.clamp': 'Clamp', 'blk.dd.clamp.desc': 'Minimum, maximum or clamp into a range',
    'blk.dd.array': 'Array Operations', 'blk.dd.array.desc': 'Append, insert, remove, find, sort and more array operations',
    'blk.dd.context': 'Context', 'blk.dd.context.desc': 'Read-only context values such as particle index, time and life',
    'blk.externalVars': 'External Variables',
    'blk.bool.true': 'True', 'blk.bool.false': 'False',
    // —— 拼图：上下文短显示名 ——
    'blk.ctx.index': 'Index', 'blk.ctx.count': 'Count', 'blk.ctx.time': 'Time',
    'blk.ctx.delta': 'Delta', 'blk.ctx.duration': 'Duration', 'blk.ctx.life': 'Life',
    'blk.ctx.uvx': 'Grid U', 'blk.ctx.uvy': 'Grid V',
    // —— 拼图：数组方法短显示名 ——
    'blk.method.push.label': 'Push', 'blk.method.insert.label': 'Insert', 'blk.method.remove.label': 'Remove',
    'blk.method.slice.label': 'Slice', 'blk.method.size.label': 'Size', 'blk.method.find.label': 'Find',
    'blk.method.includes.label': 'Includes', 'blk.method.sort.label': 'Sort', 'blk.method.unique.label': 'Unique',
    'blk.method.reverse.label': 'Reverse',
    'blk.method.push.phrase': 'Append', 'blk.method.insert.phrase': 'Insert', 'blk.method.remove.phrase': 'Remove',
    'blk.method.slice.phrase': 'Slice', 'blk.method.size.phrase': 'Length', 'blk.method.find.phrase': 'Find',
    'blk.method.includes.phrase': 'Includes', 'blk.method.sort.phrase': 'Sort', 'blk.method.unique.phrase': 'Unique',
    'blk.method.reverse.phrase': 'Reverse', 'blk.arg.array': 'Array',
    'blk.op.add': 'Add', 'blk.op.sub': 'Subtract', 'blk.op.mul': 'Multiply', 'blk.op.div': 'Divide', 'blk.op.mod': 'Modulo', 'blk.op.pow': 'Power',
    'blk.op.eq': 'Equal', 'blk.op.ne': 'Not equal', 'blk.op.lt': 'Less than', 'blk.op.le': 'Less or equal', 'blk.op.gt': 'Greater than', 'blk.op.ge': 'Greater or equal', 'blk.op.and': 'And', 'blk.op.or': 'Or',
    'blk.arg.angle': 'Angle', 'blk.arg.value': 'Value', 'blk.arg.base': 'Base', 'blk.arg.exp': 'Exponent',
    'blk.arg.lo': 'Lower bound', 'blk.arg.hi': 'Upper bound', 'blk.arg.edge': 'Edge', 'blk.arg.mod': 'Modulus',
    'blk.arg.seed': 'Seed', 'blk.arg.vec': 'Vector', 'blk.arg.axis': 'Axis', 'blk.arg.radius': 'Radius',
    'blk.slot.scale': 'Scale', 'blk.slot.light': 'Light',
    // —— 拼图：语句块 ——
    'blk.stmt.pos.label': 'Position', 'blk.stmt.pos.desc': 'Set this.position = [x, y, z]',
    'blk.stmt.pos_vec.label': 'Position', 'blk.stmt.pos_vec.desc': 'Set this.position from a vector',
    'blk.stmt.vel.label': 'Velocity', 'blk.stmt.vel.desc': 'Set this.velocity = [vx, vy, vz]',
    'blk.stmt.vel_vec.label': 'Velocity', 'blk.stmt.vel_vec.desc': 'Set this.velocity from a vector',
    'blk.stmt.col.label': 'Color', 'blk.stmt.col.desc': 'Set this.color = [r, g, b, a]',
    'blk.stmt.scl.label': 'Scale', 'blk.stmt.scl.desc': 'Set this.scale',
    'blk.stmt.glow.label': 'Glow', 'blk.stmt.glow.desc': 'Toggle this.glow',
    'blk.stmt.light.label': 'Light Level', 'blk.stmt.light.desc': 'Set this.light',
    'blk.stmt.attr.label': 'Set Property', 'blk.stmt.attr.desc': 'Set a this component (position.x/color.r/…)',
    'blk.stmt.set.label': 'Local Variable', 'blk.stmt.set.desc': 'Define a local variable and assign',
    'blk.stmt.comment.label': 'Comment', 'blk.stmt.comment.desc': 'Add a comment (not executed)',
    'blk.stmt.repeat.label': 'Repeat', 'blk.stmt.repeat.desc': 'Repeat the blocks inside forever',
    'blk.stmt.repeat_n.label': 'Repeat', 'blk.stmt.repeat_n.desc': 'Repeat the blocks inside a number of times',
    'blk.stmt.repeat_until.label': 'Repeat Until', 'blk.stmt.repeat_until.desc': 'Repeat the blocks inside until the condition is true',
    // —— 拼图：函数说明 ——
    'blk.func.sin.desc': 'Sine function', 'blk.func.cos.desc': 'Cosine function', 'blk.func.tan.desc': 'Tangent function',
    'blk.func.asin.desc': 'Arcsine function', 'blk.func.acos.desc': 'Arccosine function', 'blk.func.atan.desc': 'Arctangent function',
    'blk.func.atan2.desc': 'Arctangent function', 'blk.func.sqrt.desc': 'Square root', 'blk.func.abs.desc': 'Absolute value',
    'blk.func.sign.desc': 'Sign function (1 / -1 / 0)', 'blk.func.exp.desc': 'Exponential e^x',
    'blk.func.log.desc': 'Base-10 logarithm', 'blk.func.ln.desc': 'Natural logarithm',
    'blk.func.floor.desc': 'Round down', 'blk.func.ceil.desc': 'Round up', 'blk.func.round.desc': 'Round to nearest',
    'blk.func.fract.desc': 'Fractional part', 'blk.func.pow.desc': 'Power',
    'blk.func.min.desc': 'Minimum of two values', 'blk.func.max.desc': 'Maximum of two values',
    'blk.func.clamp.desc': 'Clamp value to a range', 'blk.func.lerp.desc': 'Linear interpolation a→b',
    'blk.func.step.desc': 'Step (returns 1 when x ≥ edge, else 0)', 'blk.func.smoothstep.desc': 'Smoothstep interpolation',
    'blk.func.mod.desc': 'Modulo (GLSL semantics)', 'blk.func.random.desc': 'Random number (0 to 1)',
    'blk.func.rand.desc': 'Deterministic pseudo-random (same seed returns the same [0,1) value)',
    'blk.func.vec.desc': 'Construct vector from components', 'blk.func.dot.desc': 'Vector dot product', 'blk.func.cross.desc': 'Vector cross product',
    'blk.func.len.desc': 'Vector length', 'blk.func.norm.desc': 'Normalize vector',
    'blk.func.rotX.desc': 'Rotation matrix around X', 'blk.func.rotY.desc': 'Rotation matrix around Y', 'blk.func.rotZ.desc': 'Rotation matrix around Z',
    'blk.func.rotAxis.desc': 'Rotation matrix around an axis', 'blk.func.polar.desc': 'Polar to vector',
    'blk.func.sphere.desc': 'Spherical to vector', 'blk.func.torus.desc': 'Torus to vector',
  },
};
